### ISSUE TITLE
Vison Processing/Tracking by week 6 - Slimelite

### ISSUE THREAD

**Issue by Dr-WaSaBi** [frc1711/Euphrosyne#25]
I think I heard Grady say that this was going to be something to be done by week 6.  But that doesn't mean we cant start thinking about it.

- [ ] Find out where the best place slimelite can be located
- [ ] Get a mount designed and fabricated
- [ ] Can we track balls with this as well?
- [ ] How would we use it in Teleop?
